apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anime-app
  template:
    metadata:
      labels:
        app: anime-app
    spec:
      containers:
      - name: anime-app-container
        image: gcr.io/credit-risk-071125/anime-project:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: anime-app-service
spec:
  type: LoadBalancer
  selector:
    app: anime-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: anime-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: anime-app
#   template:
#     metadata:
#       labels:
#         app: anime-app
#     spec:
#       containers:
#       - name: anime-app-container
#         image: gcr.io/credit-risk-071125/anime-project:latest
#         ports:
#         - containerPort: 5000  # Replace with the port your app listens on
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: anime-app-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: anime-app
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 5000