
# artifacts_root : 'artifacts'

############# DATA INGESTION #############

data_ingestion:
  bucket_name : 'my_anime_24'
  bucket_file_names :
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"
  nrows_data : 5000000

############# MODEL PARAMS #############

model:
  embedding_size: 128
  loss: 'mean_squared_error'
  optimizer: Adam
  metrics: ['mae', 'mse']

